Hlm 2074
egovernments/health-campaign-config pull request #201
Opened 2023-03-21 07:04 UTC by indroneil-egov

2023-03-23 07:19 UTC, neel-tw requested changes

2023-03-23 07:19 UTC, neel-tw commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +  "rdComplaintsByDistrictTotal": {
@indroneil-egov Please change the chart name, as it is not part of the R&D tab

2023-03-23 07:45 UTC, neel-tw approved these changes

2023-03-27 04:21 UTC, roopeshegov approved these changes

2023-03-31 05:48 UTC, neel-tw approved these changes

2023-03-31 06:15 UTC, roopeshegov approved these changes

2023-03-31 06:20 UTC, merged