(WIP)HLM-1562 | Days Inventory Stock Lasts
egovernments/health-campaign-config pull request #47
Opened 2023-02-01 15:10 UTC by bhanuprakash-egov

@neel-tw @saiprakash-eGov

2023-02-01 15:11 UTC, bhanuprakash-egov commented
> @neel-tw @saiprakash-eGov

2023-02-09 14:43 UTC, neel-tw requested changes

2023-02-09 14:43 UTC, neel-tw commented on egov-dss-dashboards/dashboard-analytics/ChartApiConfig.json
> +        "aggrQuery": "{\n  \"aggs\": {\n    \"AGGR\": {\n      \"filters\": {\n        \"filters\": {\n          \"Province filters\": {\n            \"bool\": {\n              \"must\": [\n
@bhanuprakash-egov 

- Should add size field to the "term" aggregation to get data for all regions
- Got confirmation that "RETURNED" stock will not be tracked separately. Only "Incoming" and "Outgoing" status will be available. The difference logic can be arrived using (Incoming - Outgoing)

2023-02-10 05:44 UTC, neel-tw approved these changes

2023-02-10 06:57 UTC, merged