HLM-1575 | No. of days to last inventory Bar chart
egovernments/health-campaign-config pull request #60
Opened 2023-02-08 07:20 UTC by indroneil-egov

2023-02-08 07:21 UTC, indroneil-egov commented
@neel-tw  Please review this PR.

2023-02-09 05:36 UTC, neel-tw requested changes
Have requested to remove chart config and re-use the same chart ID that is available on the overview page

2023-02-09 06:15 UTC, indroneil-egov commented
> 

Hi @neel-tw i have updated the PR with the suggested changes.

2023-02-10 08:01 UTC, neel-tw approved these changes

2023-02-10 08:01 UTC, merged